### PR TITLE
Add privoxy support

### PR DESCRIPTION
**Pull request by gokuu**
This enables the use of Privoxy to allow using the Docker container as a proxy for your browser.

This was based on the work done in https://github.com/Joentje/nordvpn-proxy.

The startup logic was also changed to use  `runsvdir` and `runsv` because both the `nordvpn` and `privoxy` commands need to be running.

Privoxy will only be enabled if the `HTTP_PROXY_PORT` env has a value, and will wait for the VPN to be connected (ie, `nordvpn status` outputs `Status: connected`) before actually starting.

### CODE REVIEW

**Comment by cyb3rl4d** [comment]
great work here gokuu, could you give any quick pointers on how I pull this change into my docker image so I can have the privoxy support to? Sorry I'm a bit of a n00b on all of this :-)

**Comment by cyb3rl4d** [comment]
How would I include this change in my docker image please? Sorry I'm a n00b at this. thanks in advance.

**Comment by gokuu** [comment]
You either need to build the image using the `Dockerfile` on this PR, or you can directly use the docker image `pedromr/nordvpn:latest` that I've already built.

In either case, to enable it, you need to provide the `HTTP_PROXY_PORT` env variable with a valid port in which to enable privoxy on that port

**Comment by cyb3rl4d** [comment]
thanks so much Gokuu for the pointer, I'll have a play. Thanks again

**Comment by bubuntux** [comment]
this looks pretty cool, but wonder if privoxy could be a separate container and route everything so it can be used independently of this container? 

i personally don't have a use for it, so i would like to keep it independent, i run this container on single board computer with very limited resources, i want to avoid add extra unnecessary process to my use case.

**Comment by pedro-rodrigues-kununu** [comment]
Honestly I don't know, I'd have to investigate it further. 
However, if you check the scripts, privoxy will only be enabled (ie, running) if the ENV variable `HTTP_PROXY_PORT` is set. Otherwise the script that would start it will exit, so no resources would be used.

**Comment by gokuu** [comment]
Sorry, replied previously with the wrong account 😅 

Honestly I don't know, I'd have to investigate it further.
However, if you check the scripts, privoxy will only be enabled (ie, running) if the ENV variable HTTP_PROXY_PORT is set. Otherwise the script that would start it will exit, so no resources would be used.

**Comment by Groofster** [comment]
Why add it to this container when you can just as easily run privoxy in the same network and a different container:

Put this in a docker-compose file and you can use privoxy from outside the container to go through the vpn.

  nordvpn:
    (usual setup)
  ports:
    - 8118:8118

  privoxy:
    image: splazit/privoxy-alpine
    container_name: privoxy
    network_mode: service:nordvpn
    depends_on:
      - nordvpn

**Comment by bulletprooffool** [comment]
> Why add it to this container when you can just as easily run privoxy in the same network and a different container:
> 
> Put this in a docker-compose file (beware of the nessecary spacing) and you can use privoxy from outside the container to go through the vpn.
> 
> nordvpn:
> (usual setup)
> ports:
> - 8118:8118
> 
> privoxy:
> image: splazit/privoxy-alpine
> container_name: privoxy
> network_mode: service:nordvpn
> depends_on:
> - nordvpn


QQ - normal setup - I have tried the following - but no love. Seems the proxy does not function - am I missing something?

```

version: "3"
services:
  vpn:
    container_name: vpn    
    image: bubuntux/nordvpn:3.7.4
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=pickme@email.com     # Required
      - PASS=${PASS}        # Required
      - CONNECT=South_Africa
      - TECHNOLOGY=NordLynx
    network_mode: bridge
    ports:
      - 8118:8118 
  
  privoxy:
    image: splazit/privoxy-alpine
    container_name: privoxy
    network_mode: service:vpn
    depends_on:
      - vpn 

```

**Comment by bulletprooffool** [comment]
Seems I can get it up and running from the new image  - and I see this message in the console:

```
2020-12-01 11:15:52.471 INFO: Privoxy will be started
2020-12-01 11:15:52.473 7fd848033100 Info: Privoxy version 3.0.28
2020-12-01 11:15:52.473 7fd848033100 Info: Program name: privoxy
2020-12-01 11:15:52.473 7fd848033100 Info: Listening on port 8118 on IP address 0.0.0.0
Info: Listening on port 8118 on IP address 0.0.0.0
```

but when I use my docker hosts ip and port 8118 as target, I see no movement.

this was my executing command to simplify this:

>  docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn             --sysctl net.ipv4.conf.all.rp_filter=2             -e USER=user@email.com -e PASS='password'             -e CONNECT=Unites_States -e TECHNOLOGY=NordLynx -e HTTP_PROXY_PORT=8118 -d pedromr/nordvpn



From the log above, I can see the session starts for the VPN (great) and I can also see that privoxy is up and running - but I am unable to target the proxy?
My Docker host has an ip on range 192.168.0.0/24 
So I am simply targetting <dockerhostip>:8118 as my intended proxy server address, but no love....

**Comment by bulletprooffool** [comment]
Never mind - forgot to expose the port:

> docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn --sysctl net.ipv4.conf.all.rp_filter=2 -e USER=user@email.com -e PASS='password' -e CONNECT=Unites_States -e TECHNOLOGY=NordLynx -e HTTP_PROXY_PORT=8118 -p8118:8118 -d pedromr/nordvpn

and voila - Simple privoxy proxy via NordLynx

**Pull request closed without merging**
