### PR TITLE
Add option to run command after successful connection

### PR DESCRIPTION
**Pull request by suhsteve**
This PR provides the ability to run custom commands/scripts after successful connections.

Users specify the command/scripts by setting the `POST_CONNECT` environment variable.

### CODE REVIEW

**Comment by bubuntux** [comment]
the change looks fine, just curious, why you need to execute a command after a successful connection ? ?
also keep in mind that it may reconnect

**Comment by suhsteve** [comment]
Thanks for merging.  Also every connection/reconnection is what I had in mind.

Imagine there is a scenario where you would want to identify yourself and your IP (also any time it changes) by calling into some external API.

**Comment by suhsteve** [comment]
I suppose it would be somewhat analogous to the [openvpn](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) `--up cmd` option.

**Comment by bubuntux** [comment]
gotcha, is gonna be in the master tag for now and is gonna be included with the next release, thanks for the pull request

**Pull request merged**
