### PR TITLE
Create tun device if it does not exist

### PR DESCRIPTION
**Pull request by wgorczyca**

### CODE REVIEW

**Comment by bubuntux** [comment]
actually i think this should always be done

>   mkdir -p /dev/net
    [[ -c /dev/net/tun ]] || mknod -m 0666 /dev/net/tun c 10 200

**Comment by bubuntux** [comment]
or maybe just when protocol is openvpn ...
do you know if wireguard use the tun dev as well ?

**Comment by wgorczyca** [comment]
> actually i think this should always be done
> 
> > mkdir -p /dev/net
> > [[ -c /dev/net/tun ]] || mknod -m 0666 /dev/net/tun c 10 200

Done, removed env variable


> or maybe just when protocol is openvpn ...
> do you know if wireguard use the tun dev as well ?

I think that wireguard also uses tun dev because I didn't want to change code at first place so I tried it and it also throws error until I create tun dev.

**Comment by bubuntux** [comment]
Thanks for the contribution @wgorczyca

**Pull request merged**
