### PR TITLE
Added traceroute to Dockerfile

### PR DESCRIPTION
**Pull request by mrsiejas**
Closes: #110

Added traceroute to the Dockerfile. Built and tested locally.

```
docker run -it nordvpn /bin/sh
# traceroute
Usage:
  traceroute [ -46dFITnreAUDV ] [ -f first_ttl ] [ -g gate,... ] [ -i device ] [ -m max_ttl ] [ -N squeries ] [ -p port ] [ -t tos ] [ -l flow_label ] [ -w MAX,HERE,NEAR ] [ -q nqueries ] [ -s src_addr ] [ -z sendwait ] [ --fwmark=num ] host [ packetlen ]
Options:
...
```

### CODE REVIEW

**Comment by obbardc** [comment]
LGTM; ps if you add "Closes: #xxx" to your commit it will auto-close that issue when the commit hits the main branch ;-)

**Comment by bubuntux** [comment]
why do we need this dependency?

**Comment by bubuntux** [comment]
i'm trying to run the container with this change and i don't see any diff, still fails for me on 3.8+ versions

any guideline ? i tried adding `--sysctl net.ipv6.conf.all.disable_ipv6=1` using openvpn protocol and so on.. but still fails for me

**Comment by bubuntux** [comment]
don't really see the point, but is a small lib that does not affect the functionally or execution process, so whatever.. 
i may remove it if i ever change the base image to alpine

**Comment by mrsiejas** [comment]
Agree. Package is decoupled from app logic and can be easily removed while can help users to troubleshoot or verify network settings.

**Comment by bubuntux** [comment]
Thanks for the contribution :+1:

**Pull request merged**
