### PR TITLE
Updating NordVPN binary and fix for #91

### PR DESCRIPTION
**Pull request by 5t4cktr4c3**
> Update nordvpn to latest

> Changed Healthcheck-URL to https://api.nordvpn.com/v1/helpers/ips/insights
> Installs additional tools for debugging and testing purposes

> Will override /etc/resolv.conf with custom nameservers if specified; fix for using the container in a custom network (#91)

### CODE REVIEW

**Comment by sUyMur** [comment]
It’s already there: https://github.com/bubuntux/nordvpn/pull/139

**Comment by bubuntux** [comment]
does the latest version just work ? i don't see any change that could fix the prev issues with it, i'm gonna have to do some tests

**Comment by janstadt** [comment]
@5t4cktr4c3 any update or info u can provide @bubuntux?

**Comment by bubuntux** [comment]
@janstadt  need to do some testing, if everything goes ok, i'll probably merge by the weekend or earlier next week , sry i'm very busy these days

**Comment by bubuntux** [comment]
@5t4cktr4c3  i manually merged some of the changes on this PR since it include a lot changes and some unrelated to the issues it was trying to fix, if you could create another PR with only the changes for #91  i can take a better look and merge

**Comment by 5t4cktr4c3** [comment]
Currently I'm working on a fork with my custom needs of your project. You might find some solutions for the issues here in my fork, however, for the moment I will stop contributing actively to this repository.

**Comment by likwid101** [comment]
Using an image on dockerhub in my unRaid setup. This works fine one a bridge network type but as soon as I change it to custom br0 it will not connect. See attached image. I assume it must be related to issue 91 and 139. Any idea a fix?

image

**Pull request closed without merging**
