### PR TITLE
Neaten password file checking

### PR DESCRIPTION
**Pull request by diinngg**
The password file check is a bit messy (my fault), I think this is neater

### CODE REVIEW

**Comment by bubuntux** [comment]
i kind of like best the way we currently get the password file

**Comment by diinngg** [comment]
I sent an email to julio.guti+github@pm.me around the time I made this pr, could you confirm that you received it?

**Comment by bubuntux** [comment]
i did received  the email, it's not a secret that the password will be output when trace debug is enabled, trace should be used to troubleshoot, verifying that he password is being properly escaped is useful, also when sharing trace you need to be mindful of that and remove the used and password from it.

**Comment by bubuntux** [comment]
Anyways, thanks for looking into it and worry about the safety of the project, this is an open source and that is the beauty of it.
and as i mention before, trace should be used only for troubleshooting.

**Comment by diinngg** [comment]
Fair enough, I will comment on those posts that I saw and leave it there then, this pr was only for that

**Comment by bubuntux** [comment]
decided to add another debug value, 
trace that will log everything but the commands that interact with the user/password
and trace+ that will log everything, hopefully this prevent ppl to accidentally share their creds

**Pull request closed without merging**
